# 01_prepare_mock_sequences.R

rm(list = ls()); gc()

#Packages
library(phyloseq)
library(Biostrings)
library(dada2)
library(tibble)
library(dplyr)
library(readr)

# Session info
message("Working directory: ", getwd())
message("R version info:")
print(sessionInfo())

# ----------------------------
# 1) Theoretical mock sequences
# ----------------------------
seq_data <- c(
  ESBL15  = "GGTCAGGCGATTGCTAACCGTTTTACAGCAAATATTAAAGGTCTGACTCAGGCTTCCCGTAACGCGAATGATGGTATTTCTGTTGCGCAGACCACTGAAGGTGCGCTGAATGAAATTAACAACAACCTGCAGCGTATTCGTGAACTTTCTGTTCAGGCAACTAACGGTACTAACTCTGACAGCGATCTTTCTTCTATCCAGGCTGAAATTACTCAACGTCTGGAAGAAATTGACCGTGTATCTGAGCAAACTCAGTTTAACGGCGTGAAAGTCCTTGCTGAAAATAATGAAATGAAAATTCAGGTTGGTGCTAATGATGGTGAAACCATCACTATCAATCTGGCAAAAATTGATGCGAAAACTCTCGGCCTGGACGGTTTTAATATCGATGGCGCGCAGAAAGCAACCGGCAGTGACCTGATTTCTAAATTTAAAGCGACAGGTACTGATAATTATCAAATTAACGGTACTGATAACTATACTGTTAATGTAGATAGTGGCGTAGTACAGGATAAAGATGGCAAACAAGTTTATGTGAGTACTGCGGATGGTTCACTTACGACCAGCAGTGATACTCAATTCAAGATTGATGCAACTAAGCTTGCAGTGGCTGCTAAAGATTTAGCTCAAGGGAATAAGATTGTCTACGAAGGTATCGAATTTACAAATACCGGCACTGTCGCTATAGATGCCAAAGGTAATGGTAAATTAACCGCCAATGTTGATGGTAAGGCTGTTGAATTCACTATTTCGGGGAGTACTGatacatcaggtactagtgcaaccgttgcccctacgacagccctatacaaaaatagtgcagggcaattgactgcaacaaaagttgaaaataaagcagcgacactatctgatcttgatctgaacgctgccaagaaaacaggaagcacgttagttgttaacggtgcaacttacgatgttagtgcagatggtaaaacgataacggagactgcttctggtaacaataaagtcatgtatctgagcaaatcagaaggtggtagcccgattctggtaaacgaagatgcagcaaaatcgttgcaatctaccaccaacccgctcgaaactatcgacaaagcattggctaaagttgacaatctgcgttctgacctcggtgcagtacaaaaccgtttcgactctgccatcaccaaccttggcaacaccvtaaacaacctgtcttctgcccgtagccgtatcgaagatgctgactacgcgaccgaagtgtc",
  ESBL21  = "GACACTTCGGTCGCATAGTCGGCGTCCTGAATACGGGACTGCGCTTCAGACAGGTTGGTGGTGGTGTTGTTCAGGTTGGTGACCGCAGAATCCAGACGGTTTTGAACGGCACCGAGGGAGGAGCGGAATTTGTCGACTTTAGCGATTGCGGCATCCAGTGCTTTTAACGGATCGGCTGTAGCGGCTCCCGCCACTTCCGCTGCACCAACAGTTACCGCCGCCGCCGTACCGGTAATGACTACAGTGGCTTCCATGTATTTACCGGTTGCAGAATCAACGACCGCATATTTAGTACTGTTAGACGCGGTGTCAGTGTAAGACAGTAAATTGACTTGTTTACCCCCAGCATCCTTGACATCCGCAGCAGCAATTGCTGTACCATCAGCAGCCGTCAGTTTCGCCGCGCTGAAATCCGCCATGCCGGACACGGTAAATCCTTTCAGATTCAAAGTGGTACTGTCGATTTGTTGCAAGCCAATGCTGATCGTCTGGTTATCATTGGCACCAATCTGAATCTTCATCGAATCGTTTTTCGACAGCACGTTCACACCGTTGAACTGGGTCTGACCAGATACACGGTCAATTTCATCAAGACGGGATTTGATTTCGTCCTGAATAGAAGACAGGTCGGAATCAGAGTTCGTGCCGGTAGAGGCCTGAACGGTCAGTTCACGAATACGCTGCAAGTTGTTGTTAATCTCTGACAGCGCGCCTTCAGCCGTCTGCGCCAGAGAAATACCGTCGTTGGCGTTACGTGCGGCCTGAGTCAGACCTTTGATGTTAGAAGTAAAGCGGTTAGCAATCGCCTGGCC",
  ESBL25  = "GGTCAGGCGATTGCTAACCGTTTTACTTCTAATATTAAAGGCCTGACTCAGGCTGCACGTAACGCCAATGACGGTATTTCTGTTGCACAGACCACTGAAGGCGCGCTGTCCGAAATCAACAACAACTTACAGCGTATTCGTGAACTGACGGTTCAGGCCACTACAGGGACTAACTCCGATTCTGACCTGGACTCCATCCAGGACGAAATCAAATCTCGTCTGGACGAAATTGACCGCGTATCCGGTCAGACCCAGTTCAACGGCGTGAACGTGCTGTCCAAAGATGGTTCAATGAAAATTCAGGTCGGCGCAAATGATGGTGAAACCATCACGATTGATCTGAAGAAAATTGACTCTGATACGCTGAATCTGGCTGGTTTTAACGTGAATGGCGAAGGTGAAACAGCCAATACTGCTGCAACACTTAAAGATATGGTTGGTTTAAAACTCGATAATACGGGGGTCACTACAGCTGGAGTTAATAGATATATTGCTGACAAAGCCGTCGCAAGTAGCACGGATATTTTGAATGCGGTAGCTGGTGTTGATGGCAGTAAAGTTTCCACGGAGGCAGATGTTGGTTTTGGTGCAGCTGCCCCTGGTACGCCAGTGGAATATACTTATCATAAAGATACTAACACATATACGGCTTCTGCTTCAGTTGATGCGACTCAACTGGCGGCATTCCTGAATCCTGAAGCGGGTGGTACCACTGCTGCAACAGTAAGTATTGGCAACGGTACAACAGCTCAAGAGCAAAAAGTCATTATTGCTAAAGATGGTTCTTTAACTGCTGCTGATGACGGTGCCGCTCTCTATCTTGATGATACTGGTAACTTAAGTAAAACTAACGCAGGCACTGATACTCAAGCTAAACTGTCTGACTTAATGGCAAACAATGCTAATGCCAAAACAGTCATTACAACAGATAAAGGTACATTTACTGCTAATACGACAAAGTTTGATGGGGTAGATATTTCTGTTGATGCTTCAACGTTTGCTAACGCCGTTAAAAATGAGACTTACACTGCAACTGTTGGTGTAACTTTACCTGCGACATATACAGTCAATAATGGCACTGCTGCATCAGCGTATTTAGTCGATGGAAAAGTGAGCAAAACTCCTGCCGAGTATTTTGCTCAAGCTGATGGCACTATTACTAGTGGTGAAAATGCGGCTACCAGTAAAGCTATCTATGTAAGTGCCAATGGTAACTTAACGACTAATACAACTAGTGAATCTGAAGCTACTACCAACCCGCTGGCAGCATTGGATGACGCTATCGCGTCTATCGACAAATTCCGTTCTTCCCTGGGTGCTATCCAGAACCGTCTGGATTCCGCAGTCACCAACCTGAACAACACCACTACCAACCTGTCTGAAGCGCAGTCCCGTATTCAGGACGCCGACTATGCGACCGAAGTGTC",
  ESBL01  = "GGCCAGGCGATTGCTAACCGCTTTACTTCTAACATCAAAGGTCTGACTCAGGCCGCACGTAACGCCAACGACGGTATTTCTCTGGCGCAGACGGCTGAAGGCGCGCTGTCAGAGATTAACAACAACTTGCAGCGTATTCGTGAACTGACCGTTCAGGCCTCTACCGGCACGAACTCTGATTCCGACCTGTCTTCTATTCAGGACGAAATCAAATCCCGTCTTGATGAAATTGACCGTGTATCTGGTCAGACCCAGTTCAACGGTGTGAACGTGCTGTCGAAAAACGATTCGATGAAGATTCAGATTGGTGCCAATGATAACCAGACGATCAGCATTGGCTTGCAACAAATCGACAGTACCACTTTGAATCTGAAAGGATTTACCGTGTCCGGCATGGCGGATTTCAGCGCGGCGAAACTGACGGCTGCTGATGGTACAGCAATTGCTGCTGCGGATGTcaaggatgctgggggtaaacaagtcaatttactgtcttacactgacaccgcgtctaacagtactaaatatgcggtcgttgattctgcaaccggtaaatacatggaagccactgtagtcattaccggtacggcggcggcggtaactgttggtgcagcggaagtggcgggagccgctacagccgatccgttaaaagcactggatgccgcaatcgctaaagtcgacaaattccgctcctccctcggtgccgttcaaaaccgtctggattctgcggtcaccaacctgaacaacaccaccaccaacctgtctgaagcgcagtcccgtattcaggacgccgactatgcgaccgaagtgtc",
  KPC_1   = "GGCCAGGCGATTGCTAACCGCTTTACTTCTAACATCAAAGGTCTGACTCAGGCCGCACGTAACGCCAACGACGGTATTTCTCTGGCGCAGACGGCTGAAGGCGCGCTGTCAGAGATTAACAACAACTTGCAGCGTATTCGTGAACTGACCGTTCAGGCCTCTACCGGCACGAACTCTGATTCCGACCTGTCTTCTATTCAGGACGAAATCAAATCCCGTCTTGATGAAATTGACCGTGTATCTGGTCAGACCCAGTTCAACGGTGTGAACGTGCTGTCGAAAAACGATTCGATGAAGATTCAGATTGGTGCCAATGATAACCAGACGATCAGCATTGGCTTGCAACAAATCGACAGTACCACTTTGAATCTGAAAGGATTTACCGTGTCCGGCATGGCGGATTTCAGCGCGGCGAAACTGACGGCTGCTGATGGTACAGCAATTGCTGCTGCGGATGTcaaggatgctgggggtaaacaagtcaatttactgtcttacactgacaccgcgtctaacagtactaaatatgcggtcgttgattctgcaaccggtaaatacatggaagccactgtagtcattaccggtacggcggcggcggtaactgttggtgcagcggaagtggcgggagccgctacagccgatccgttaaaagcactggatgccgcaatcgctaaagtcgacaaattccgctcctccctcggtgccgttcaaaaccgtctggattctgcggtcaccaacctgaacaacaccaccaccaacctgtctgaagcgcagtcccgtattcaggacgccgactatgcgaccgaagtgtc",
  Oxa48_1 = "GGTCAGGCGATTGCTAACCGTTTTACCTCTAACATCAAGGGCCTGACTCAGGCTGCACGTAACGCCAACGACGGTATTTCTGTTGCACAGACCACCGAAGGCGCGCTGTCTGAAATCAACAACAACTTACAGCGTATTCGTGAACTGACGGTTCAGGCCACTACAGGGACTAACTCCGATTCTGACCTGGACTCCATCCAGGACGAAATCAAATCTCGTCTGGACGAAATTGACCGCGTATCCGGTCAGACCCAGTTCAACGGCGTGAACGTGCTGTCTAAAGATGGCTCGATGAAAATTCAGGTCGGCGCGAACGATGGCGAAACGATTACTATTGATCTGAAGAAAATTGACTCTGATACGCTGAATCTGGCTGGTTTTAACGTTAACGGTAAAGGTTCTGTAGCGAATACAGCTGCGACAAGCGACGATTTAAAACTGGCTGGTTTCACTAAGGGCACCACAGATACCAATGGCGTGACCGCGTATACAAACACAATTAGTAATGACAAAGCCAAAGCTTCCGATCTGTTAGCTAATATCACCGATGGATCAGTGATCACTGGGGGAGGGGCAAACGCTTTTGGCGTGGCTGCAAAGAATGGTTACACCTATGATGCAGCAAGTAAATCTTATAGTTTTGCTGCAGATGGTGCCGATTCAGCGAAGACGTTAAGCATCATTAATCCAAACACCGGTGATTCGTCGCAGGCGACAGTGACTATTGGTGGTAAAGAGCAGAAAGTTAATATTTCCCAGGATGGAAAAATTACTGCGGCAGATGATAATGCGACGCTGTATTTAGATAAACAGGGAAACTTGACAAAAACGAATGCAGGTAACGATACCGCAGCGACTTGGGATGGTTTAATTTCCAACAGCGATTCTACCGGTGCGGTTCCAGTTGGGGTTGCAACTACAATTACAATTACTTCTGGTACAGCTTCCGGAATGTCTGTTCAGTCCGCAGGAGCAGGAATTCAGACCTCAACAAATTCTCAGATTCTTGCAGGTGGTGCATTTGCGGCTAAGGTAAGTATTGAGGGAGGCGCTGCTACAGACATTTTGGTAGCAAGTAATGGAAACATAACAGCGGCTGATGGTAATGCACTTTATCTTGATGCGACTACTGGTGGATTCACTACAACGGCTGGAGGAAATACAGCTGCTTCGTTAGATAATTTAATTGCTAACAGTAAGGATGCTACCTTAACCGTAACTTCAGGTACCGGCCAGAACACTGTTTATAGCACAACAGGAAGTGGCGCTCAGTTCACCAGTTTAGCAAAAGTAGACACTGTCAATGTCACCAACGCACATGTCAGTGCCGAAGGTATGGCAAATCTGACAAAAAGCAATTTTACCATTGATATGGGCGGTACAGGTACAGTAACTTACACAGTTTCCAATGGGGATGTGAAAGCTGCTGCAAATGCTGATGTTTATGTCGAAGATGGTGCACTTTCAGCCAATGCTACAAAAGATGTAACCTACTTTGAACAAAAAAATGGGGCTATTACCAACAGCACCGGTGGTACCATCTATGAAACAGCTGATGGTAAGTTAACAACAGAAGCCACTACTGCATCCAGTTCCACCGCCGATCCCCTGAAAGCTCTGGACGAAGCCATCAGCTCCATCGACAAATTCCGCTCCTCCCTCGGTGCGGTTCAAAACCGTCTGGATTCCGCGGTCACCAACCTGAACAACACCACTACCAACCTGTCTGAAGCGCAGTCCCGTATTCAGGACGCCGACTATGCGACCGAAGTGTC"
)

fliC_mock_seqs <- DNAStringSet(seq_data)

# ----------------------------
# 2) Build minimal phyloseq object 
# ----------------------------
strains <- names(fliC_mock_seqs)
samples <- "MockMix"

#Creation of OTU matrix for phyloseq object
otu_matrix <- matrix(1,
                     nrow = length(strains),
                     ncol = length(samples),
                     dimnames = list(strains, samples)
)

otu_prop <- apply(otu_matrix, 2, function(x) x / sum(x))
otu_ps <- otu_table(otu_prop, taxa_are_rows = TRUE)

#Assigning taxonomy for phyloseq object

### Define taxonomy ranks
tax_ranks <- c("Kingdom","Phylum","Class","Order",
               "Family","Genus","Species")

### Taxonomy lineage for E. coli
ecoli_tax <- c("Bacteria", "Pseudomonadota", "Gammaproteobacteria",
               "Enterobacterales", "Enterobacteriaceae",
               "Escherichia", "Escherichia coli")

### Repeat taxonomy for all strains
tax_matrix <- matrix(
  rep(ecoli_tax, times = length(strains)),
  nrow = length(strains),
  ncol = length(ecoli_tax),
  byrow = TRUE,
  dimnames = list(strains, tax_ranks)
)

tax_ps <- tax_table(tax_matrix)

## Defining sample type data for phyloseq

sample_ps <- sample_data(data.frame(
  Sample_Type = "Theoretical_Mock",
  row.names = samples
))

ps_mock_manu <- phyloseq(otu_ps, tax_ps, sample_ps, fliC_mock_seqs)

# ----------------------------
# 3) Trim primers 
# ----------------------------
fwd_p <- "GGTCAGGCGATTGCTAACCG"
rev_p <- "GACACTTCGGTCGCGTAGTC"

raw_ref_seqs <- refseq(ps_mock_manu)

trimmed_ref_seqs <- Biostrings::trimLRPatterns(
  Lpattern = fwd_p,
  Rpattern = dada2:::rc(rev_p),
  subject = raw_ref_seqs,
  max.Lmismatch = 2,
  max.Rmismatch = 2
)

ps_mock_trimmed <- ps_mock_manu
ps_mock_trimmed@refseq <- trimmed_ref_seqs

# ----------------------------
# 4) Filter to the 4 strains of interest
# ----------------------------
keep_strains <- c("ESBL15", "ESBL25", "KPC_1", "Oxa48_1")

ps_mock_trimmed_4 <- prune_taxa(keep_strains, ps_mock_trimmed)

# ----------------------------
# 5) Store outputs (FASTA + report + optional RDS)
# ----------------------------
out_dir <- "/users/acatala3/first_step/pilot_analysis/theoretical_mock/results"

# FASTA with the 4 trimmed sequences
writeXStringSet(refseq(ps_mock_trimmed_4),
                filepath = file.path(out_dir, "mock_trimmed_4.fasta"),
                format = "fasta"
)

# Report table (raw vs trimmed, and whether kept)
report <- tibble(
  Strain = names(raw_ref_seqs),
  Raw_Length = width(raw_ref_seqs),
  Trimmed_Length = width(trimmed_ref_seqs),
  Kept = Strain %in% keep_strains
) %>% arrange(desc(Kept), Strain)

write_tsv(report, file.path(out_dir, "mock_trim_report.tsv"))

# Save phyloseq objects for downstream steps
saveRDS(ps_mock_trimmed_4, file.path(out_dir, "ps_mock_trimmed_4.rds"))

message("Done ✅ Outputs in: ", out_dir)


